// Mocks generated by Mockito 5.4.6 from annotations
// in smartchefai/test/helpers/mock_firebase_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:smartchefai/models/models.dart' as _i5;
import 'package:smartchefai/services/firebase_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserCredential_0 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i3.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false)
          as bool);

  @override
  _i4.Stream<_i2.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i2.User?>.empty(),
          )
          as _i4.Stream<_i2.User?>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.DetectedIngredient>> analyzeImage(_i6.XFile? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [imageFile]),
            returnValue: _i4.Future<List<_i5.DetectedIngredient>>.value(
              <_i5.DetectedIngredient>[],
            ),
          )
          as _i4.Future<List<_i5.DetectedIngredient>>);

  @override
  _i4.Future<_i2.UserCredential> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> registerWithEmail(
    String? email,
    String? password,
    String? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [email, password, name]),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#registerWithEmail, [email, password, name]),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Recipe>> getAllRecipes({
    int? limit = 100,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipes, [], {
              #limit: limit,
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i4.Future<List<_i5.Recipe>>.value(<_i5.Recipe>[]),
          )
          as _i4.Future<List<_i5.Recipe>>);

  @override
  _i4.Future<_i5.Recipe?> getRecipe(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipe, [recipeId]),
            returnValue: _i4.Future<_i5.Recipe?>.value(),
          )
          as _i4.Future<_i5.Recipe?>);

  @override
  _i4.Future<List<_i5.Recipe>> searchRecipes(
    String? query, {
    int? limit = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRecipes, [query], {#limit: limit}),
            returnValue: _i4.Future<List<_i5.Recipe>>.value(<_i5.Recipe>[]),
          )
          as _i4.Future<List<_i5.Recipe>>);

  @override
  _i4.Future<List<_i5.Recipe>> searchByIngredients(
    List<String>? ingredients, {
    int? limit = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchByIngredients,
              [ingredients],
              {#limit: limit},
            ),
            returnValue: _i4.Future<List<_i5.Recipe>>.value(<_i5.Recipe>[]),
          )
          as _i4.Future<List<_i5.Recipe>>);

  @override
  _i4.Future<void> createUserProfile({
    required String? name,
    required String? email,
    List<String>? dietaryPreferences,
    List<String>? allergies,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserProfile, [], {
              #name: name,
              #email: email,
              #dietaryPreferences: dietaryPreferences,
              #allergies: allergies,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.AppUser?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i5.AppUser?>.value(),
          )
          as _i4.Future<_i5.AppUser?>);

  @override
  _i4.Future<void> updatePreferences({
    required List<String>? dietaryPreferences,
    required List<String>? allergies,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [], {
              #dietaryPreferences: dietaryPreferences,
              #allergies: allergies,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.AppUser?> incrementRecipesCooked() =>
      (super.noSuchMethod(
            Invocation.method(#incrementRecipesCooked, []),
            returnValue: _i4.Future<_i5.AppUser?>.value(),
          )
          as _i4.Future<_i5.AppUser?>);

  @override
  _i4.Future<String> uploadProfilePhoto(_i6.XFile? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [imageFile]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePhoto, [imageFile]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> removeProfilePhoto() =>
      (super.noSuchMethod(
            Invocation.method(#removeProfilePhoto, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getFavoriteIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteIds, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<void> addFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#addFavorite, [recipeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavorite, [recipeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> toggleFavorite(String? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [recipeId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> createGroceryList({
    required String? name,
    required List<_i5.GroceryItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroceryList, [], {
              #name: name,
              #items: items,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createGroceryList, [], {
                  #name: name,
                  #items: items,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<List<_i5.GroceryList>> getGroceryLists() =>
      (super.noSuchMethod(
            Invocation.method(#getGroceryLists, []),
            returnValue: _i4.Future<List<_i5.GroceryList>>.value(
              <_i5.GroceryList>[],
            ),
          )
          as _i4.Future<List<_i5.GroceryList>>);

  @override
  _i4.Future<_i5.GroceryList?> getGroceryList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#getGroceryList, [listId]),
            returnValue: _i4.Future<_i5.GroceryList?>.value(),
          )
          as _i4.Future<_i5.GroceryList?>);

  @override
  _i4.Future<void> updateGroceryList(
    String? listId, {
    String? name,
    List<_i5.GroceryItem>? items,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateGroceryList,
              [listId],
              {#name: name, #items: items},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteGroceryList(String? listId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGroceryList, [listId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleGroceryItem(String? listId, String? itemName) =>
      (super.noSuchMethod(
            Invocation.method(#toggleGroceryItem, [listId, itemName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addSearchHistory(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#addSearchHistory, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getSearchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getSearchHistory, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i5.MealPlan?> getMealPlan() =>
      (super.noSuchMethod(
            Invocation.method(#getMealPlan, []),
            returnValue: _i4.Future<_i5.MealPlan?>.value(),
          )
          as _i4.Future<_i5.MealPlan?>);

  @override
  _i4.Future<void> saveMealPlan(_i5.MealPlan? plan) =>
      (super.noSuchMethod(
            Invocation.method(#saveMealPlan, [plan]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.NutritionGoals?> getNutritionGoals() =>
      (super.noSuchMethod(
            Invocation.method(#getNutritionGoals, []),
            returnValue: _i4.Future<_i5.NutritionGoals?>.value(),
          )
          as _i4.Future<_i5.NutritionGoals?>);

  @override
  _i4.Future<void> saveNutritionGoals(_i5.NutritionGoals? goals) =>
      (super.noSuchMethod(
            Invocation.method(#saveNutritionGoals, [goals]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );
}
